// swift-tools-version:5.10
import PackageDescription
import Foundation

// The engine (HyperfocalKit), vendored Adobe DNG SDK, and CLI live here as a
// SwiftPM package. The Hyperfocal app itself is an Xcode target (generated by
// XcodeGen from project.yml) that depends on this package.
//
// Cross-platform note: on Apple platforms the engine decodes/encodes through
// ImageIO/CoreImage and registers through Vision. On Linux those frameworks
// don't exist, so the engine talks to a C-ABI shim (`CImaging`) over
// libtiff/libpng/libjpeg-turbo/LibRaw/lcms2/exiv2/OpenCV. See
// Docs/cross-platform-plan.md.

// Split a pkg-config invocation's output into individual flags. Run at manifest
// evaluation time so the multiarch include/lib paths come from the system,
// not hardcoded. Returns [] if pkg-config isn't present (non-Linux hosts).
func pkgConfig(_ mode: String, _ packages: [String]) -> [String] {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = ["pkg-config", mode] + packages
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    guard (try? proc.run()) != nil else { return [] }
    proc.waitUntilExit()
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let text = String(data: data, encoding: .utf8) ?? ""
    return text.split(whereSeparator: { $0 == " " || $0 == "\n" || $0 == "\t" })
        .map(String.init).filter { !$0.isEmpty }
}

// True if pkg-config knows the package (exit status 0). Used to detect an
// optional OpenCV install on macOS for the Phase 1.5 registration A/B — absent
// it, macOS builds Vision-only exactly as before.
func pkgExists(_ pkg: String) -> Bool {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = ["pkg-config", "--exists", pkg]
    proc.standardError = FileHandle.nullDevice
    guard (try? proc.run()) != nil else { return false }
    proc.waitUntilExit()
    return proc.terminationStatus == 0
}

// Platform flag the vendored DNG SDK selects its OS layer on (dng_flags.h has
// first-class qLinux support; only zlib is linked — XMP/JPEG/JXL are compiled
// out via the qDNG* defines below).
#if os(macOS)
let dngPlatformDefine: CXXSetting = .define("qMacOS", to: "1")
#elseif os(Linux)
let dngPlatformDefine: CXXSetting = .define("qLinux", to: "1")
#else
let dngPlatformDefine: CXXSetting = .define("qWinOS", to: "1")
#endif

// HyperfocalKit dependencies: the DNG SDK everywhere, plus the imaging shim on
// non-Apple platforms (appended below).
var hyperfocalKitDeps: [Target.Dependency] = ["CDNGSDK"]
var extraTargets: [Target] = []
var extraProducts: [Product] = []

// HyperfocalKit's own build settings, extended per-platform below.
var kitSwiftSettings: [SwiftSetting] = [
    // The engine's per-pixel loops are ~30-50x slower at -Onone — a 45MP depth
    // regularization goes from ~30s to tens of minutes. Keep the engine
    // optimized even in Debug builds; the app layer stays debuggable.
    .unsafeFlags(["-O"], .when(configuration: .debug)),
]

// The shared model layer as a real module (cross-platform-plan 0d): the
// probe, the Qt bridge, and (eventually) the Linux shell consume it as a
// dependency. The Mac app still compiles the same files directly into its
// target (App/project.yml path reference) — no module boundary there.
// -enable-testing in every configuration so the probe's @testable import
// works: the probe is a white-box regression harness, and its deep reach
// into model internals must not force those internals public — the public
// surface is defined by real shell clients (the bridge).
// Off Apple, ObservableObject/@Published come from OpenCombine.
var appCoreDeps: [Target.Dependency] = ["HyperfocalKit"]
#if !os(macOS)
appCoreDeps.append(.product(name: "OpenCombine", package: "OpenCombine"))
// `import zlib` is an Apple-SDK module; elsewhere ProjectStore's crc32 comes
// from a minimal system-library shim over <zlib.h>.
appCoreDeps.append("CZlib")
extraTargets.append(.systemLibrary(name: "CZlib", path: "Sources/CZlib"))
#endif
extraTargets.append(
    .target(
        name: "AppCore",
        dependencies: appCoreDeps,
        path: "AppCore",
        swiftSettings: [.unsafeFlags(["-enable-testing"])]
    )
)
// C-ABI bridge the Qt shell drives (cross-platform-plan Phase 2): a
// SwiftPM dynamic library so one product definition serves macOS and
// Linux. A development artifact for the Qt shell — never shipped with
// the Mac app.
extraTargets.append(
    .target(
        name: "HyperfocalBridge",
        dependencies: ["AppCore", "HyperfocalKit"],
        path: "Bridge"
    )
)
extraProducts.append(
    .library(name: "HyperfocalBridge", type: .dynamic,
             targets: ["HyperfocalBridge"])
)

#if os(macOS)
// The probe drives AppKit-side checks too (pasteboards, CG parity) —
// macOS only; the Linux gate is the CLI synth→fuse→compare path.
extraTargets.append(
    .executableTarget(
        name: "retouch-probe",
        dependencies: ["AppCore", "HyperfocalKit"],
        path: "Probe"
    )
)
// Phase 1.5 registration A/B (Docs/cross-platform-plan.md decision 2):
// HYPERFOCAL_OPENCV_AB=1 at build time compiles a small OpenCV-only
// registration target so the fusion pipeline can run OpenCV registration on
// macOS and be compared against Vision on identical frames; selected at
// runtime via HYPERFOCAL_REGISTER=opencv (see Aligner). Explicitly opt-in,
// never auto-detected: with Homebrew OpenCV merely installed, auto-linking
// put its ad-hoc-signed dylibs into HyperfocalKit and thus the *app*, whose
// library validation rightly refuses them (different Team IDs) — dyld killed
// the app at launch. The A/B is a CLI-only affair; the app must always build
// Vision-only. Homebrew ships OpenCV 5 (module `opencv5`); Linux/older
// installs use `opencv4`. Take whichever pkg-config knows.
if ProcessInfo.processInfo.environment["HYPERFOCAL_OPENCV_AB"] == "1",
   let cvPkg = ["opencv5", "opencv4"].first(where: pkgExists) {
    extraTargets.append(
        .target(
            name: "COpenCVRegister",
            path: "Sources/COpenCVRegister",
            publicHeadersPath: "include",
            cxxSettings: [
                .unsafeFlags(pkgConfig("--cflags", [cvPkg])),
                .unsafeFlags(["-Wno-deprecated-declarations"]),
            ],
            linkerSettings: [
                .unsafeFlags(pkgConfig("--libs", [cvPkg])),
                .linkedLibrary("c++"),
            ]
        )
    )
    hyperfocalKitDeps.append("COpenCVRegister")
    kitSwiftSettings.append(.define("HYPERFOCAL_HAVE_OPENCV"))
}
#elseif os(Linux)
// The C-ABI imaging shim over the system libraries. pkg-config supplies the
// (multiarch) include and link flags at manifest-eval time.
let imagingPkgs = ["libtiff-4", "libpng", "libjpeg", "lcms2", "libraw", "opencv4", "exiv2"]
extraTargets.append(
    .target(
        name: "CImaging",
        path: "Sources/CImaging",
        publicHeadersPath: "include",
        cxxSettings: [
            .unsafeFlags(pkgConfig("--cflags", imagingPkgs)),
            .unsafeFlags(["-Wno-deprecated-declarations"]),
        ],
        linkerSettings: [
            // LibRaw's pkg-config Libs line carries compile flags (-fopenmp,
            // -pthread) the Swift link driver rejects; map them to the runtime
            // libraries they imply so LibRaw's parallel decode still links.
            .unsafeFlags(pkgConfig("--libs", imagingPkgs).map {
                switch $0 {
                case "-fopenmp": return "-lgomp"
                case "-pthread": return "-lpthread"
                default: return $0
                }
            }),
            .linkedLibrary("stdc++"),
        ]
    )
)
hyperfocalKitDeps.append("CImaging")
#endif

var targets: [Target] = [
    .target(
        name: "CDNGSDK",
        path: "Vendor/dng_sdk",
        exclude: [
            "DNG_ReadMe.txt",
            "source/dng_validate.cpp",
            "source/dng_jxl.cpp",
            "source/dng_xmp.cpp",
            "source/dng_xmp_sdk.cpp",
            "source/dng_update_meta.cpp",
            "jxl_headers",
        ],
        sources: ["source", "shim"],
        publicHeadersPath: "include",
        cxxSettings: [
            .headerSearchPath("source"),
            .headerSearchPath("jxl_headers"),
            dngPlatformDefine,
            .define("qDNGUseXMP", to: "0"),
            .define("qDNGXMPFiles", to: "0"),
            .define("qDNGXMPDocOps", to: "0"),
            .define("qDNGUseLibJPEG", to: "0"),
            .define("qDNGValidate", to: "0"),
            .define("NDEBUG"),
            // Adobe's code references APIs deprecated since macOS 10.5;
            // not ours to fix. (unsafeFlags would block use of this package
            // as a remote dependency — acceptable for an app repo.)
            .unsafeFlags(["-Wno-deprecated-declarations"]),
        ],
        linkerSettings: [
            .linkedLibrary("z"),
        ]
    ),
    .target(
        name: "HyperfocalKit",
        dependencies: hyperfocalKitDeps,
        swiftSettings: kitSwiftSettings
    ),
    .executableTarget(
        name: "hyperfocal-cli",
        dependencies: [
            "HyperfocalKit",
            .product(name: "ArgumentParser", package: "swift-argument-parser"),
        ]
    ),
]
targets.append(contentsOf: extraTargets)

let package = Package(
    name: "HyperfocalKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "HyperfocalKit", targets: ["HyperfocalKit"]),
        .executable(name: "hyperfocal-cli", targets: ["hyperfocal-cli"]),
    ] + extraProducts,
    dependencies: {
        var deps: [Package.Dependency] = [
            .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
        ]
        #if !os(macOS)
        // ObservableObject/@Published for AppCore off Apple platforms.
        deps.append(.package(url: "https://github.com/OpenCombine/OpenCombine.git",
                             from: "0.14.0"))
        #endif
        return deps
    }(),
    targets: targets,
    cxxLanguageStandard: .cxx17
)
