// swift-tools-version:5.10
import PackageDescription

// The engine (HyperfocalKit), vendored Adobe DNG SDK, and CLI live here as a
// SwiftPM package. The Hyperfocal app itself is an Xcode target (generated by
// XcodeGen from project.yml) that depends on this package.
let package = Package(
    name: "HyperfocalKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "HyperfocalKit", targets: ["HyperfocalKit"]),
        .executable(name: "hyperfocal-cli", targets: ["hyperfocal-cli"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
    ],
    targets: [
        .target(
            name: "CDNGSDK",
            path: "Vendor/dng_sdk",
            exclude: [
                "DNG_ReadMe.txt",
                "source/dng_validate.cpp",
                "source/dng_jxl.cpp",
                "source/dng_xmp.cpp",
                "source/dng_xmp_sdk.cpp",
                "source/dng_update_meta.cpp",
                "jxl_headers",
            ],
            sources: ["source", "shim"],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("source"),
                .headerSearchPath("jxl_headers"),
                .define("qMacOS", to: "1"),
                .define("qDNGUseXMP", to: "0"),
                .define("qDNGXMPFiles", to: "0"),
                .define("qDNGXMPDocOps", to: "0"),
                .define("qDNGUseLibJPEG", to: "0"),
                .define("qDNGValidate", to: "0"),
                .define("NDEBUG"),
                // Adobe's code references APIs deprecated since macOS 10.5;
                // not ours to fix. (unsafeFlags would block use of this package
                // as a remote dependency — acceptable for an app repo.)
                .unsafeFlags(["-Wno-deprecated-declarations"]),
            ],
            linkerSettings: [
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "HyperfocalKit",
            dependencies: ["CDNGSDK"],
            swiftSettings: [
                // The engine's per-pixel loops are ~30-50x slower at -Onone —
                // a 45MP depth regularization goes from ~30s to tens of
                // minutes. Keep the engine optimized even in Debug builds;
                // the app layer stays debuggable.
                .unsafeFlags(["-O"], .when(configuration: .debug)),
            ]
        ),
        .executableTarget(
            name: "hyperfocal-cli",
            dependencies: [
                "HyperfocalKit",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
        // Compiles the shared model layer (AppCore/) headless — the same
        // files the app target compiles (App/project.yml references them by
        // path). One source of truth; do not copy them anywhere.
        .executableTarget(
            name: "retouch-probe",
            dependencies: ["HyperfocalKit"],
            path: ".",
            sources: ["Probe/main.swift", "AppCore/AppModel.swift",
                      "AppCore/Stack.swift", "AppCore/ProjectStore.swift",
                      "AppCore/RetouchSession.swift"]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
