// swift-tools-version:5.10
import PackageDescription
import Foundation

// The engine (HyperfocalKit), vendored Adobe DNG SDK, and CLI live here as a
// SwiftPM package. The Hyperfocal app itself is an Xcode target (generated by
// XcodeGen from project.yml) that depends on this package.
//
// Cross-platform note: on Apple platforms the engine decodes/encodes through
// ImageIO/CoreImage and registers through Vision. On Linux those frameworks
// don't exist, so the engine talks to a C-ABI shim (`CImaging`) over
// libtiff/libpng/libjpeg-turbo/LibRaw/lcms2/exiv2/OpenCV. See
// Docs/cross-platform-plan.md.

// Split a pkg-config invocation's output into individual flags. Run at manifest
// evaluation time so the multiarch include/lib paths come from the system,
// not hardcoded. Returns [] if pkg-config isn't present (non-Linux hosts).
func pkgConfig(_ mode: String, _ packages: [String]) -> [String] {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = ["pkg-config", mode] + packages
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    guard (try? proc.run()) != nil else { return [] }
    proc.waitUntilExit()
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    let text = String(data: data, encoding: .utf8) ?? ""
    return text.split(whereSeparator: { $0 == " " || $0 == "\n" || $0 == "\t" })
        .map(String.init).filter { !$0.isEmpty }
}

// Platform flag the vendored DNG SDK selects its OS layer on (dng_flags.h has
// first-class qLinux support; only zlib is linked — XMP/JPEG/JXL are compiled
// out via the qDNG* defines below).
#if os(macOS)
let dngPlatformDefine: CXXSetting = .define("qMacOS", to: "1")
#elseif os(Linux)
let dngPlatformDefine: CXXSetting = .define("qLinux", to: "1")
#else
let dngPlatformDefine: CXXSetting = .define("qWinOS", to: "1")
#endif

// HyperfocalKit dependencies: the DNG SDK everywhere, plus the imaging shim on
// non-Apple platforms (appended below).
var hyperfocalKitDeps: [Target.Dependency] = ["CDNGSDK"]
var extraTargets: [Target] = []

#if os(macOS)
// The shared model layer (AppCore/) compiled headless — the same files the app
// target compiles (App/project.yml references them by path). AppKit-backed, so
// macOS only; the Linux gate is the CLI synth→fuse→compare path instead.
extraTargets.append(
    .executableTarget(
        name: "retouch-probe",
        dependencies: ["HyperfocalKit"],
        path: ".",
        sources: ["Probe/main.swift", "AppCore/AppModel.swift",
                  "AppCore/Stack.swift", "AppCore/ProjectStore.swift",
                  "AppCore/RetouchSession.swift",
                  "AppCore/DialogService.swift"]
    )
)
#elseif os(Linux)
// The C-ABI imaging shim over the system libraries. pkg-config supplies the
// (multiarch) include and link flags at manifest-eval time.
let imagingPkgs = ["libtiff-4", "libpng", "libjpeg", "lcms2", "libraw", "opencv4", "exiv2"]
extraTargets.append(
    .target(
        name: "CImaging",
        path: "Sources/CImaging",
        publicHeadersPath: "include",
        cxxSettings: [
            .unsafeFlags(pkgConfig("--cflags", imagingPkgs)),
            .unsafeFlags(["-Wno-deprecated-declarations"]),
        ],
        linkerSettings: [
            // LibRaw's pkg-config Libs line carries compile flags (-fopenmp,
            // -pthread) the Swift link driver rejects; map them to the runtime
            // libraries they imply so LibRaw's parallel decode still links.
            .unsafeFlags(pkgConfig("--libs", imagingPkgs).map {
                switch $0 {
                case "-fopenmp": return "-lgomp"
                case "-pthread": return "-lpthread"
                default: return $0
                }
            }),
            .linkedLibrary("stdc++"),
        ]
    )
)
hyperfocalKitDeps.append("CImaging")
#endif

var targets: [Target] = [
    .target(
        name: "CDNGSDK",
        path: "Vendor/dng_sdk",
        exclude: [
            "DNG_ReadMe.txt",
            "source/dng_validate.cpp",
            "source/dng_jxl.cpp",
            "source/dng_xmp.cpp",
            "source/dng_xmp_sdk.cpp",
            "source/dng_update_meta.cpp",
            "jxl_headers",
        ],
        sources: ["source", "shim"],
        publicHeadersPath: "include",
        cxxSettings: [
            .headerSearchPath("source"),
            .headerSearchPath("jxl_headers"),
            dngPlatformDefine,
            .define("qDNGUseXMP", to: "0"),
            .define("qDNGXMPFiles", to: "0"),
            .define("qDNGXMPDocOps", to: "0"),
            .define("qDNGUseLibJPEG", to: "0"),
            .define("qDNGValidate", to: "0"),
            .define("NDEBUG"),
            // Adobe's code references APIs deprecated since macOS 10.5;
            // not ours to fix. (unsafeFlags would block use of this package
            // as a remote dependency — acceptable for an app repo.)
            .unsafeFlags(["-Wno-deprecated-declarations"]),
        ],
        linkerSettings: [
            .linkedLibrary("z"),
        ]
    ),
    .target(
        name: "HyperfocalKit",
        dependencies: hyperfocalKitDeps,
        swiftSettings: [
            // The engine's per-pixel loops are ~30-50x slower at -Onone —
            // a 45MP depth regularization goes from ~30s to tens of
            // minutes. Keep the engine optimized even in Debug builds;
            // the app layer stays debuggable.
            .unsafeFlags(["-O"], .when(configuration: .debug)),
        ]
    ),
    .executableTarget(
        name: "hyperfocal-cli",
        dependencies: [
            "HyperfocalKit",
            .product(name: "ArgumentParser", package: "swift-argument-parser"),
        ]
    ),
]
targets.append(contentsOf: extraTargets)

let package = Package(
    name: "HyperfocalKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "HyperfocalKit", targets: ["HyperfocalKit"]),
        .executable(name: "hyperfocal-cli", targets: ["hyperfocal-cli"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
    ],
    targets: targets,
    cxxLanguageStandard: .cxx17
)
