#!/usr/bin/env python3
"""Flatten Localizable.xcstrings into the catalogs the non-Apple builds read.

App/Resources/Localizable.xcstrings is the single hand-maintained source of
truth for every user-facing string in both UIs (see CLAUDE.md). The macOS app
consumes it directly; nothing else can, so this script emits:

  QtShell/i18n/<lang>.json          the Qt shell's CatalogTranslator maps
  Sources/HyperfocalKit/GeneratedStrings.swift
                                    the table AppCore/Kit resolve against
                                    off Apple, where Foundation has no
                                    catalog to read

Both outputs are checked in, so Windows and Linux builds need neither Python
nor Qt Linguist. Re-run after every catalog edit; Scripts/check-translations.sh
fails the build when they have drifted.

Usage:  Scripts/gen-translations.py [--check]
        --check  exit 1 if the outputs would change (no writes)
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, 'App/Resources/Localizable.xcstrings')
QT_DIR = os.path.join(ROOT, 'QtShell/i18n')
SWIFT_OUT = os.path.join(ROOT, 'Sources/HyperfocalKit/GeneratedStrings.swift')

# The shipping languages. Adding one here without backfilling every key is a
# bug the coverage gate reports.
LANGUAGES = ['de', 'es', 'fr', 'it', 'ja', 'ko', 'nl', 'pt-BR', 'ru',
             'zh-Hans']

# Field separator inside the generated Swift blobs. U+0001 cannot occur in a
# user-facing string, so no escaping scheme is needed on the parse side.
SEP = '\u0001'


def load_catalog():
    with open(CATALOG, encoding='utf-8') as f:
        return json.load(f)


def translations(catalog):
    """{lang: {key: value}} for every entry that has a real translation.

    Plural/device *variations* are skipped: they carry no single string, and
    the two consumers here (a Qt label, a headless Swift lookup) both take
    the English source for those. Only AppKit/SwiftUI resolves variations,
    and that path reads the catalog directly."""
    out = {lang: {} for lang in LANGUAGES}
    for key, entry in sorted(catalog['strings'].items()):
        locs = entry.get('localizations', {})
        for lang in LANGUAGES:
            unit = locs.get(lang, {}).get('stringUnit')
            if not unit:
                continue
            value = unit.get('value', '')
            if unit.get('state') == 'translated' and value:
                out[lang][key] = value
    return out


def qt_payload(table):
    # sort_keys for a stable diff; ensure_ascii=False keeps the file readable
    # and roughly a third smaller than \u-escaped output.
    return json.dumps(table, ensure_ascii=False, sort_keys=True,
                      indent=0, separators=(',', ':')) + '\n'


def swift_literal(text):
    """A Swift string literal for arbitrary catalog text."""
    out = ['"']
    for ch in text:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20:
            # Includes SEP itself, which is how the blob's field breaks
            # survive into the literal.
            out.append('\\u{%x}' % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return ''.join(out)


def swift_payload(tables):
    lines = [
        '// Generated by Scripts/gen-translations.py — DO NOT EDIT.',
        '//',
        '// Translations for the platforms where Foundation has no string',
        '// catalog to read. On Apple, `localizedString` goes to the app',
        '// bundle and never touches this table; off Apple it is the only',
        '// source of localized text, including everything the Qt shell',
        '// renders from AppCore (status, errors, dialogs, undo names).',
        '//',
        '// Source of truth: App/Resources/Localizable.xcstrings. Edit that,',
        '// then re-run the generator.',
        '',
        'enum GeneratedStrings {',
        '    /// Language tags with at least one translation, most specific',
        '    /// first per language (the resolver strips region itself).',
        '    static let languages: [String] = [',
    ]
    langs = [l for l in LANGUAGES if tables[l]]
    for lang in langs:
        lines.append('        "%s",' % lang)
    lines.append('    ]')
    lines.append('')
    lines.append('    /// key\\u{1}value\\u{1}… — one flat blob per language.')
    lines.append('    /// A blob rather than a dictionary literal: a literal')
    lines.append('    /// of this size is pathological for the type checker,')
    lines.append('    /// while a string literal costs it nothing and parses')
    lines.append('    /// once, lazily, on first lookup.')
    lines.append('    static func blob(for language: String) -> String? {')
    lines.append('        switch language {')
    for lang in langs:
        lines.append('        case "%s": return %s' % (lang, ident(lang)))
    lines.append('        default: return nil')
    lines.append('        }')
    lines.append('    }')
    for lang in langs:
        table = tables[lang]
        parts = []
        for key in sorted(table):
            # The blob is positional, so a stray separator inside a string
            # would silently shift every field after it.
            if SEP in key or SEP in table[key]:
                raise ValueError('U+0001 in catalog string: %r' % key)
            parts.append(key)
            parts.append(table[key])
        lines.append('')
        lines.append('    // %s — %d strings' % (lang, len(table)))
        lines.append('    private static let %s: String =' % ident(lang))
        lines.append('        %s' % swift_literal(SEP.join(parts)))
    lines.append('}')
    return '\n'.join(lines) + '\n'


def ident(lang):
    return 'lang_' + lang.replace('-', '_')


def emit(path, text, check):
    old = None
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            old = f.read()
    if old == text:
        return False
    if check:
        print('stale: %s' % os.path.relpath(path, ROOT), file=sys.stderr)
        return True
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)
    print('wrote %s' % os.path.relpath(path, ROOT))
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if any output is stale; write nothing')
    args = ap.parse_args()

    tables = translations(load_catalog())
    stale = False
    for lang in LANGUAGES:
        path = os.path.join(QT_DIR, '%s.json' % lang)
        stale |= emit(path, qt_payload(tables[lang]), args.check)
    stale |= emit(SWIFT_OUT, swift_payload(tables), args.check)

    if args.check and stale:
        print('Generated translations are stale — run '
              'Scripts/gen-translations.py', file=sys.stderr)
        return 1
    if not args.check:
        for lang in LANGUAGES:
            print('  %-8s %d strings' % (lang, len(tables[lang])))
    return 0


if __name__ == '__main__':
    sys.exit(main())
