#!/usr/bin/env python3
"""Assemble the third-party notice bundle for wgpu-native and its Rust crates.

The wgpu compute backend ships as a prebuilt `wgpu_native.dll`, and that
release archive contains **no license text at all** — headers, libraries and a
version stamp, nothing else. But the DLL is a Rust static link: ~140 crates end
up inside it, and MIT (the arm we elect nearly everywhere) requires each crate's
copyright notice to travel with the binary. So we generate the bundle
ourselves, from the same data `cargo license` reads.

What it does, given the tag pinned in `Scripts/fetch-wgpu.sh`:

  1. fetches that tag's `Cargo.lock` from the wgpu-native repository,
  2. asks crates.io for each crate's SPDX license expression,
  3. downloads each `.crate` archive and extracts the license files it ships,
  4. for the crates that ship none — a sizeable minority, since the registry
     only requires the `license` field — records the upstream repository, so
     the copyright statement stays findable, and falls back to the canonical
     SPDX text for the elected arm,
  5. writes `licenses/wgpu-native-ThirdPartyNotices.txt` — every component with
     its version, SPDX expression and the arm we elect, then the verbatim
     license texts, deduplicated (one copy of Apache-2.0 rather than ninety).

This needs the network, so it is NOT part of any build: the output is checked
in, exactly like the generated translation catalogs, and regenerated by hand
when the wgpu pin moves. `--check` is the offline half — it verifies the bundle
was generated for the tag currently pinned, which is what stops a wgpu bump
from shipping stale attribution. That check runs from `Scripts/ci-gate.sh` and
`Scripts/package-windows.ps1`.

Usage:  Scripts/gen-wgpu-notices.py [--check]
        --check  exit 1 if the bundle is missing or built for another tag
                 (offline)
"""

import argparse
import io
import json
import os
import re
import sys
import tarfile
import time
import urllib.request

# Windows consoles default to a legacy code page that cannot encode the
# checkmark this prints on success — the gate would then fail on its own
# success message. Same guard as check-translations.py and gen-notices.py.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(encoding='utf-8', errors='replace')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FETCH = os.path.join(ROOT, 'Scripts', 'fetch-wgpu.sh')
OUT = os.path.join(ROOT, 'licenses', 'wgpu-native-ThirdPartyNotices.txt')
REPO = 'https://raw.githubusercontent.com/gfx-rs/wgpu-native'
SPDX_TEXT = 'https://raw.githubusercontent.com/spdx/license-list-data/main/text'
UA = {'User-Agent': 'hyperfocal-notice-generator (+https://github.com/ethannicholas/hyperfocal)'}
TAG_LINE = '# wgpu-native tag: '

# License files a crate might ship, in no particular order — anything matching
# is included verbatim.
LICENSE_FILE = re.compile(r'^(LICEN[CS]E|COPYING|NOTICE|UNLICENSE)', re.IGNORECASE)

# Which arm of a multi-licensed crate the binary is distributed under. MIT
# first: it is Hyperfocal's own license, so electing it keeps the shipped
# obligations to attribution alone. The order below is preference, not
# ranking — every entry is permissive.
ELECTION_ORDER = ['MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause',
                  'ISC', 'Zlib', 'Unlicense', 'CC0-1.0']


def pinned_tag():
    """The single source of truth for which wgpu-native we ship."""
    with open(FETCH, encoding='utf-8') as f:
        match = re.search(r'^TAG=(\S+)$', f.read(), re.MULTILINE)
    if not match:
        sys.exit(f'gen-wgpu-notices: no TAG= line in {FETCH}')
    return match.group(1)


def recorded_tag():
    if not os.path.exists(OUT):
        return None
    with open(OUT, encoding='utf-8') as f:
        for line in f:
            if line.startswith(TAG_LINE):
                return line[len(TAG_LINE):].strip()
    return None


def get(url, binary=False):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA),
                                timeout=60) as response:
        data = response.read()
    return data if binary else data.decode('utf-8')


def elect(spdx):
    """Pick the arm we distribute under from an SPDX expression.

    `AND` means every listed license applies at once, so there is nothing to
    elect — the whole expression is reported and every text bundled.
    """
    if not spdx:
        return None
    if ' AND ' in spdx.replace('(', ' ').replace(')', ' '):
        return spdx
    arms = {a.strip(' ()') for a in re.split(r'\s+OR\s+|/', spdx)}
    for candidate in ELECTION_ORDER:
        if candidate in arms:
            return candidate
    return spdx


def crate_licenses(name, version):
    """Every license file the published crate ships, as {filename: text}."""
    url = f'https://crates.io/api/v1/crates/{name}/{version}/download'
    archive = tarfile.open(fileobj=io.BytesIO(get(url, binary=True)), mode='r:gz')
    found = {}
    for member in archive.getmembers():
        parts = member.name.split('/')
        if len(parts) != 2 or not member.isfile():
            continue                       # only the crate root
        if not LICENSE_FILE.match(parts[1]):
            continue
        extracted = archive.extractfile(member)
        if extracted is None:
            continue
        found[parts[1]] = extracted.read().decode('utf-8', errors='replace')
    return found


def generate(tag):
    print(f'gen-wgpu-notices: wgpu-native {tag}', file=sys.stderr)
    lock = get(f'{REPO}/{tag}/Cargo.lock')
    packages = re.findall(
        r'^\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"',
        lock, re.MULTILINE)

    components = []      # (name, version, spdx, elected)
    texts = {}           # license text -> [component label, ...]
    unbundled = []       # (label, elected, repository) for crates shipping none
    spdx_cache = {}

    def add_text(text, label):
        text = text.replace('\r\n', '\n').strip()
        if text:
            texts.setdefault(text, []).append(label)

    def canonical(spdx_id):
        """The SPDX license list's text, for crates that ship none."""
        if spdx_id not in spdx_cache:
            try:
                spdx_cache[spdx_id] = get(f'{SPDX_TEXT}/{spdx_id}.txt')
            except Exception:                      # noqa: BLE001
                spdx_cache[spdx_id] = None
        return spdx_cache[spdx_id]

    for index, (name, version) in enumerate(packages, 1):
        label = f'{name} {version}'
        print(f'  [{index}/{len(packages)}] {label}', file=sys.stderr)
        if name == 'wgpu-native':
            # Not published to crates.io — it is the repository itself.
            spdx = 'MIT OR Apache-2.0'
            for filename in ('LICENSE.MIT', 'LICENSE.APACHE'):
                if elect(spdx) in filename or filename == 'LICENSE.MIT':
                    add_text(get(f'{REPO}/{tag}/{filename}'), label)
                    break
            components.append((name, version, spdx, elect(spdx)))
            continue
        meta = json.loads(get(f'https://crates.io/api/v1/crates/{name}/{version}'))
        spdx = meta['version']['license']
        elected = elect(spdx)
        components.append((name, version, spdx, elected))
        files = crate_licenses(name, version)
        # Prefer the file matching the elected arm (crates conventionally ship
        # LICENSE-MIT and LICENSE-APACHE side by side); otherwise take
        # everything, which is also what an `AND` expression requires.
        preferred = [fn for fn in files
                     if elected and elected.split('-')[0].upper() in fn.upper()]
        for filename in (preferred or sorted(files)):
            add_text(files[filename], f'{label} ({filename})')
        if not files:
            # No text in the archive: keep the component attributable by
            # naming where its copyright statement lives, and bundle the
            # canonical text of the arm it is distributed under.
            # The version endpoint carries no repository link; ask the crate
            # endpoint, but only for these few.
            try:
                info = json.loads(get(f'https://crates.io/api/v1/crates/{name}'))
                repository = (info.get('crate') or {}).get('repository') or ''
            except Exception:                      # noqa: BLE001
                repository = ''
            unbundled.append((label, elected, repository))
            text = canonical(elected) if elected and ' ' not in elected else None
            if text:
                add_text(text, f'{label} (SPDX {elected}; archive ships no text)')
            print(f'    ! no license file in the {label} archive', file=sys.stderr)
        time.sleep(0.2)                    # be polite to the registry

    lines = [
        'Third-party notices: wgpu-native and its Rust dependency graph',
        '=' * 62,
        '',
        'The GPU compute backend on Windows and Linux is wgpu-native, which is',
        'statically linked from Rust and therefore carries its whole dependency',
        'graph inside `wgpu_native.dll`. Every component is listed below with the',
        'license arm Hyperfocal distributes it under, followed by the license',
        'texts themselves. Nothing here is under a copyleft license.',
        '',
        'This file is GENERATED — do not edit it by hand. Regenerate it with',
        '`Scripts/gen-wgpu-notices.py` whenever the wgpu pin in',
        '`Scripts/fetch-wgpu.sh` changes; `--check` verifies the two agree.',
        '',
        TAG_LINE + tag,
        f'# components: {len(components)}',
        '',
        'Components',
        '-' * 62,
        '',
    ]
    width = max(len(f'{n} {v}') for n, v, _, _ in components)
    for name, version, spdx, elected in sorted(components):
        label = f'{name} {version}'.ljust(width)
        used = '' if elected == spdx else f'  [used under: {elected}]'
        lines.append(f'  {label}  {spdx}{used}')
    if unbundled:
        lines += [
            '',
            'Components whose published archive ships no license file',
            '-' * 62,
            '',
            'The crates.io registry requires the `license` field, not a license',
            'FILE, so some crates publish only the former. Each is distributed',
            'under the license named below, whose canonical text is included in',
            'the next section; the upstream repository is given so the',
            "component's own copyright statement stays findable.",
            '',
        ]
        for label, elected, repository in sorted(unbundled):
            lines.append(f'  {label} - {elected}')
            if repository:
                lines.append(f'      {repository}')
    lines += ['', 'License texts', '-' * 62, '']
    for text, labels in sorted(texts.items(), key=lambda kv: -len(kv[1])):
        lines.append('=' * 62)
        lines.append('Applies to:')
        lines += [f'  {label}' for label in sorted(labels)]
        lines += ['=' * 62, '', text, '']

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'✓ wrote {os.path.relpath(OUT, ROOT)} '
          f'({len(components)} components, {len(texts)} distinct license texts)')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='offline: verify the bundle matches the pinned tag')
    args = parser.parse_args()
    tag = pinned_tag()
    if args.check:
        have = recorded_tag()
        if have is None:
            sys.exit(f'wgpu notices missing or unstamped ({os.path.relpath(OUT, ROOT)}) '
                     '- run Scripts/gen-wgpu-notices.py')
        if have != tag:
            sys.exit(f'wgpu notices are for {have}, but Scripts/fetch-wgpu.sh pins {tag} '
                     '- run Scripts/gen-wgpu-notices.py')
        print(f'✓ wgpu notices match the pinned tag ({tag})')
        return
    generate(tag)


if __name__ == '__main__':
    main()
