#!/bin/sh
# Builds a distribution-ready Hyperfocal.app into dist/, plus .zip and .dmg,
# via the Xcode project (App/Hyperfocal.xcodeproj — generated by XcodeGen).
#
#   Scripts/package-app.sh [options]
#
#   --sign "IDENTITY"      codesign identity (default: auto-detect a
#                          "Developer ID Application" cert, else ad-hoc)
#   --notarize PROFILE     submit via a notarytool keychain profile and staple
#                          (requires a Developer ID signature)
#   --no-archives          build only the .app (skip .zip/.dmg)
#
#   VERSION=x.y.z          override the marketing version (default: latest git
#                          tag, else the project.yml value)
set -e
cd "$(dirname "$0")/.."

IDENTITY=""
NOTARIZE_PROFILE=""
ARCHIVES=1
while [ $# -gt 0 ]; do
    case "$1" in
        --sign) IDENTITY="$2"; shift ;;
        --notarize) NOTARIZE_PROFILE="$2"; shift ;;
        --no-archives) ARCHIVES=0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

VERSION="${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo 1.0.0)}"
VERSION="${VERSION#v}"  # tags are v1.0.0; CFBundleShortVersionString must be bare integers
BUILD_NUMBER=$(git rev-list --count HEAD 2>/dev/null || echo 1)

if [ -z "$IDENTITY" ]; then
    IDENTITY=$(security find-identity -v -p codesigning 2>/dev/null \
        | grep "Developer ID Application" | head -1 | sed 's/.*"\(.*\)"/\1/')
fi

if [ ! -d App/Hyperfocal.xcodeproj ] || [ ! -f App/Hyperfocal.entitlements ]; then
    (cd App && xcodegen generate)
fi

echo "== building Hyperfocal $VERSION ($BUILD_NUMBER)"
# Sign ad-hoc during the build; the real (or ad-hoc) signature is applied to
# the final bundle below. Release config builds universal (ARCHS_STANDARD).
xcodebuild -project App/Hyperfocal.xcodeproj -scheme Hyperfocal \
    -configuration Release -derivedDataPath .build/xcode \
    CODE_SIGN_IDENTITY="-" CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM="" \
    MARKETING_VERSION="$VERSION" CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO \
    build | grep -E "^\*\* BUILD" || { echo "build failed" >&2; exit 1; }

APP=dist/Hyperfocal.app
mkdir -p dist
rm -rf "$APP"
cp -R .build/xcode/Build/Products/Release/Hyperfocal.app "$APP"

# --entitlements on every re-sign: --force replaces the signature wholesale,
# and without it the App Sandbox entitlements from the build would be dropped.
ENTITLEMENTS=App/Hyperfocal.entitlements
if [ -n "$IDENTITY" ]; then
    echo "== signing with: $IDENTITY (hardened runtime)"
    codesign --force --options runtime --timestamp \
        --entitlements "$ENTITLEMENTS" -s "$IDENTITY" "$APP"
else
    echo "== no Developer ID certificate found; signing ad-hoc"
    echo "   (other Macs will show the Gatekeeper unidentified-developer prompt)"
    codesign --force --entitlements "$ENTITLEMENTS" -s - "$APP"
fi
codesign --verify --strict "$APP"

if [ -n "$NOTARIZE_PROFILE" ]; then
    if [ -z "$IDENTITY" ]; then
        echo "error: notarization requires a Developer ID signature" >&2
        exit 1
    fi
    echo "== notarizing (profile: $NOTARIZE_PROFILE)"
    NOTARIZE_ZIP=$(mktemp -d)/Hyperfocal.zip
    ditto -c -k --keepParent "$APP" "$NOTARIZE_ZIP"
    xcrun notarytool submit "$NOTARIZE_ZIP" --keychain-profile "$NOTARIZE_PROFILE" --wait
    xcrun stapler staple "$APP"
fi

if [ "$ARCHIVES" = 1 ]; then
    ZIP=dist/Hyperfocal-$VERSION.zip
    DMG=dist/Hyperfocal-$VERSION.dmg
    rm -f "$ZIP" "$DMG"
    ditto -c -k --keepParent "$APP" "$ZIP"

    STAGING=$(mktemp -d)/Hyperfocal
    mkdir -p "$STAGING"
    cp -R "$APP" "$STAGING/"
    ln -s /Applications "$STAGING/Applications"
    hdiutil create -volname Hyperfocal -srcfolder "$STAGING" -ov -quiet -format UDZO "$DMG"
    echo "== artifacts:"
    ls -la dist/ | grep -v "^total\|^d" | awk '{print "   " $NF " (" $5 " bytes)"}'
fi

echo "built $APP"
